[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
debug = true

[profile.test]
#opt-level = 1
#lto = true
#debug = true

[dependencies]
itertools = "0.13.0"
arrayvec = "0.7.6"
max_n = "0.1.0"
num = "0.4.3"
regex = "1.11.1"